const express=require("express"); const mongoose=require("mongoose"); const Match=require("../models/Match"); const Member=require("../models/Member"); const {requireAuth}=require("../middleware/auth"); const {evaluateMatch}=require("../utils/scoring"); const {matchQuery}=require("../services/statisticsService"); const {asyncRoute,ok,fail}=require("../utils/api");
const router=express.Router(); router.use(requireAuth); const populate=q=>q.populate("sideA sideB createdBy","name color avatarUrl role");
function payload(body){ return {format:body.format,sideA:body.sideA,sideB:body.sideB,games:body.games,isCustom:Boolean(body.isCustom)}; }
async function validateMembers(ids){ if(ids.some(id=>!mongoose.isValidObjectId(id))) return false; return (await Member.countDocuments({_id:{$in:ids},status:"active"}))===ids.length; }
router.get("/",asyncRoute(async(req,res)=>{const query=matchQuery(req.query); if(req.query.date){const start=new Date(`${req.query.date}T00:00:00`),end=new Date(`${req.query.date}T23:59:59.999`);query.playedAt={$gte:start,$lte:end};} const matches=await populate(Match.find(query)).sort({playedAt:-1}).limit(Math.min(Number(req.query.limit)||100,200)).lean();return ok(res,{matches});}));
router.get("/:id",asyncRoute(async(req,res)=>{const match=await populate(Match.findOne({_id:req.params.id,deletedAt:null})).lean(); return match?ok(res,{match}):fail(res,404,"MATCH_NOT_FOUND","Match not found.");}));
router.post("/",asyncRoute(async(req,res)=>{const evaluated=evaluateMatch(payload(req.body));if(evaluated.error)return fail(res,400,"INVALID_SCORE",evaluated.error);if(!await validateMembers([...evaluated.sideA,...evaluated.sideB]))return fail(res,400,"INVALID_PLAYERS","Choose active players."); const match=await Match.create({...evaluated,format:req.body.format,isCustom:Boolean(req.body.isCustom),note:req.body.note||"",playedAt:req.body.playedAt?new Date(req.body.playedAt):new Date(),createdBy:req.member._id,editHistory:[{member:req.member._id,action:"created"}]});await populate(match);return ok(res,{match},201);}));
router.patch("/:id",asyncRoute(async(req,res)=>{const match=await Match.findOne({_id:req.params.id,deletedAt:null});if(!match)return fail(res,404,"MATCH_NOT_FOUND","Match not found.");if(String(match.createdBy)!==String(req.member._id)&&req.member.role!=="admin")return fail(res,403,"FORBIDDEN","Only the creator or admin may edit this match.");const evaluated=evaluateMatch(payload(req.body));if(evaluated.error)return fail(res,400,"INVALID_SCORE",evaluated.error);if(!await validateMembers([...evaluated.sideA,...evaluated.sideB]))return fail(res,400,"INVALID_PLAYERS","Choose active players.");Object.assign(match,evaluated,{format:req.body.format,isCustom:Boolean(req.body.isCustom),note:req.body.note||"",playedAt:req.body.playedAt?new Date(req.body.playedAt):match.playedAt});match.editHistory.push({member:req.member._id,action:"edited"});await match.save();await populate(match);return ok(res,{match});}));
router.delete("/:id",asyncRoute(async(req,res)=>{if(req.member.role!=="admin")return fail(res,403,"ADMIN_REQUIRED","Only an admin may delete matches.");const match=await Match.findOne({_id:req.params.id,deletedAt:null});if(!match)return fail(res,404,"MATCH_NOT_FOUND","Match not found.");match.deletedAt=new Date();match.deletedBy=req.member._id;await match.save();return ok(res,{message:"Match deleted."});})); module.exports=router;
